### ISSUE TITLE
Please make CBC launch with VS2 Beta 11

### ISSUE THREAD

**Issue by NullHarp** [Cannoneers-of-Create/CreateBigCannons#192]
Valkyrien Skies beta 11 causes cbc to fail to correctly load on game launch, it would be very nice if this was fixed as it fixes a critical flaw with the way the Afterblazer block from VS: Clockwork saves and prevents world corruption.

**Comment by rbasamoyai** [comment]
Could you please post a log?

**Comment by NullHarp** [comment]
[01May2023 14:29:36.399] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, NullHarp, --version, 1.18.2, --gameDir, C:/Users/smith/AppData/Roaming/PrismLauncher/instances/Cogfight Official Modpack/minecraft, --assetsDir, C:/Users/smith/AppData/Roaming/PrismLauncher/assets, --assetIndex, 1.18, --uuid, d9349843a41041cfa95144cf1a03b8a5, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width, 854, --height, 480]
[01May2023 14:29:36.406] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.4 by Oracle Corporation
[01May2023 14:29:36.531] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/smith/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2348!/ Service=ModLauncher Env=CLIENT
[01May2023 14:29:36.996] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\smith\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.0\fmlcore-1.18.2-40.2.0.jar is missing mods.toml file
[01May2023 14:29:37.002] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\smith\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.0\javafmllanguage-1.18.2-40.2.0.jar is missing mods.toml file
[01May2023 14:29:37.007] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\smith\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.0\lowcodelanguage-1.18.2-40.2.0.jar is missing mods.toml file
[01May2023 14:29:37.012] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\smith\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.0\mclanguage-1.18.2-40.2.0.jar is missing mods.toml file
[01May2023 14:29:37.440] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 27 dependencies adding them to mods collection
[01May2023 14:29:38.883] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[01May2023 14:29:38.952] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2, --gameDir, C:\Users\smith\AppData\Roaming\PrismLauncher\instances\Cogfight Official Modpack\minecraft, --assetsDir, C:\Users\smith\AppData\Roaming\PrismLauncher\assets, --uuid, d9349843a41041cfa95144cf1a03b8a5, --username, NullHarp, --assetIndex, 1.18, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[01May2023 14:29:39.039] [main/INFO] [Rubidium/]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[01May2023 14:29:39.045] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 28 options available, 1 override(s) found
[01May2023 14:29:39.306] [main/WARN] [Rubidium/]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [oculus]) disables it and children
[01May2023 14:29:39.802] [main/WARN] [mixin/]: Error loading class: dev/ftb/mods/ftbchunks/data/ClaimedChunkManager (java.lang.ClassNotFoundException: dev.ftb.mods.ftbchunks.data.ClaimedChunkManager)
[01May2023 14:29:39.853] [main/WARN] [mixin/]: Error loading class: com/sonicether/soundphysics/SoundPhysics (java.lang.ClassNotFoundException: com.sonicether.soundphysics.SoundPhysics)
[01May2023 14:29:39.866] [main/WARN] [mixin/]: Error loading class: blusunrize/immersiveengineering/common/gui/BlockEntityInventory (java.lang.ClassNotFoundException: blusunrize.immersiveengineering.common.gui.BlockEntityInventory)
[01May2023 14:29:39.867] [main/WARN] [mixin/]: Error loading class: cofh/core/block/entity/TileCoFH (java.lang.ClassNotFoundException: cofh.core.block.entity.TileCoFH)
[01May2023 14:29:39.867] [main/WARN] [mixin/]: Error loading class: li/cil/tis3d/common/entity/InfraredPacketEntity (java.lang.ClassNotFoundException: li.cil.tis3d.common.entity.InfraredPacketEntity)
[01May2023 14:29:39.875] [main/WARN] [mixin/]: Error loading class: li/cil/tis3d/client/renderer/tileentity/CasingTileEntityRenderer (java.lang.ClassNotFoundException: li.cil.tis3d.client.renderer.tileentity.CasingTileEntityRenderer)
[01May2023 14:29:39.875] [main/WARN] [mixin/]: Error loading class: li/cil/tis3d/client/renderer/RenderContextImpl (java.lang.ClassNotFoundException: li.cil.tis3d.client.renderer.RenderContextImpl)
[01May2023 14:29:46.458] [Render thread/WARN] [mixin/]: Method overwrite conflict for m_85995_ in mixins.oculus.vertexformat.json:block_rendering.MixinBufferBuilder_SeparateAo, previously written by me.jellysquid.mods.sodium.mixin.features.buffer_builder.intrinsics.MixinBufferBuilder. Skipping method.
[01May2023 14:29:47.213] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/smith/AppData/Roaming/PrismLauncher/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2369!/assets/.mcassetsroot' uses unexpected schema
[01May2023 14:29:47.214] [Render thread/WARN] [net.minecraft.server.packs.VanillaPackResources/]: Assets URL 'union:/C:/Users/smith/AppData/Roaming/PrismLauncher/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar%2369!/data/.mcassetsroot' uses unexpected schema
[01May2023 14:29:47.263] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[01May2023 14:29:47.703] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: NullHarp
[01May2023 14:29:47.833] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 SNAPSHOT
[01May2023 14:29:48.490] [Render thread/INFO] [Oculus/]: ARB_direct_state_access detected, enabling DSA.
[01May2023 14:29:48.491] [Render thread/INFO] [Oculus/]: Debug functionality is disabled.
[01May2023 14:29:48.508] [Render thread/INFO] [Oculus/]: Shaders are disabled because no valid shaderpack is selected
[01May2023 14:29:48.508] [Render thread/INFO] [Oculus/]: Shaders are disabled
[01May2023 14:29:48.795] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[01May2023 14:29:48.829] [modloading-worker-0/INFO] [Advanced Peripherals/]: AdvancedPeripherals says hello!
[01May2023 14:29:48.932] [modloading-worker-0/INFO] [Advanced Peripherals/]: botania not loaded, skip integration loading
[01May2023 14:29:48.933] [modloading-worker-0/WARN] [Advanced Peripherals/]: Failed to load integration for botania
[01May2023 14:29:48.933] [modloading-worker-0/WARN] [Advanced Peripherals/]: Successfully loaded integration for create
[01May2023 14:29:48.943] [modloading-worker-0/INFO] [Advanced Peripherals/]: mekanism not loaded, skip integration loading
[01May2023 14:29:48.944] [modloading-worker-0/WARN] [Advanced Peripherals/]: Failed to load integration for mekanism
[01May2023 14:29:48.954] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[01May2023 14:29:48.978] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[01May2023 14:29:49.074] [modloading-worker-0/INFO] [com.jozufozu.flywheel.backend.Backend/]: Oculus detected.
[01May2023 14:29:49.472] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[01May2023 14:29:50.562] [modloading-worker-0/INFO] [thedarkcolour.kotlinforforge.test.KotlinForForge/]: Kotlin For Forge Enabled!
[01May2023 14:29:50.860] [modloading-worker-0/INFO] [com.tterrag.registrate.AbstractRegistrate/]: Detected new forge version, registering events reflectively.
[01May2023 14:29:50.866] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 40.2.0, for MC 1.18.2 with MCP 20220404.173914
[01May2023 14:29:50.866] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v40.2.0 Initialized
[01May2023 14:29:51.887] [modloading-worker-0/WARN] [mixin/]: @Inject(@At("INVOKE_ASSIGN")) Shift.BY=2 on vs_clockwork-common.mixins.json:compat.block.MixinRedstoneContactBlock::handler$zko000$injectTick exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[01May2023 14:29:57.963] [Render thread/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[01May2023 14:29:57.967] [Render thread/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[01May2023 14:29:58.831] [Render thread/INFO] [Oculus/]: Hardware information:
[01May2023 14:29:58.832] [Render thread/INFO] [Oculus/]: CPU: 6x AMD Ryzen 5 3500 6-Core Processor 
[01May2023 14:29:58.832] [Render thread/INFO] [Oculus/]: GPU: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 528.02)
[01May2023 14:29:58.832] [Render thread/INFO] [Oculus/]: OS: Windows 10 (10.0)
[01May2023 14:29:59.455] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[01May2023 14:29:59.926] [Render thread/INFO] [net.minecraft.server.packs.resources.ReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources
[01May2023 14:30:01.025] [Worker-Main-10/WARN] [net.minecraft.client.sounds.SoundManager/]: File vs_clockwork:sounds/thick_fluid_swim.ogg does not exist, cannot add it to event vs_clockwork:thick_fluid_swim
[01May2023 14:30:01.025] [Worker-Main-10/WARN] [net.minecraft.client.sounds.SoundManager/]: File vs_clockwork:sounds/thick_fluid_fill.ogg does not exist, cannot add it to event vs_clockwork:thick_fluid_fill
[01May2023 14:30:01.025] [Worker-Main-10/WARN] [net.minecraft.client.sounds.SoundManager/]: File vs_clockwork:sounds/thick_fluid_empty.ogg does not exist, cannot add it to event vs_clockwork:thick_fluid_empty
[01May2023 14:30:06.567] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:steel_catwalk' referenced from: alloyed:steel_catwalk#bottom=true,east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: minecraft:models/steel_catwalk.json
[01May2023 14:30:06.572] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_tri_way' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_tri_way.json
[01May2023 14:30:06.573] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_post' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_post.json
[01May2023 14:30:06.574] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_straight' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_straight.json
[01May2023 14:30:06.574] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_end' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_end.json
[01May2023 14:30:06.574] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_corner' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_corner.json
[01May2023 14:30:06.574] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'createdeco:block/chainlink_fence_four_way' referenced from: alloyed:steel_mesh_fence#east=true,north=true,south=true,waterlogged=true,west=true: java.io.FileNotFoundException: createdeco:models/block/chainlink_fence_four_way.json
[01May2023 14:30:09.153] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'minecraft:valkyrienskies' referenced from: valkyrienskies:test_flap#facing=north: java.io.FileNotFoundException: minecraft:models/valkyrienskies.json
[01May2023 14:30:11.216] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'valkyrienskies:ship_assembler#inventory' referenced from: valkyrienskies:ship_assembler#inventory: java.io.FileNotFoundException: valkyrienskies:models/item/ship_assembler.json
[01May2023 14:30:12.921] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/end
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/four_way
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/corner
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missing in vs_clockwork:block/physics_infuser/zap
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/straight
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/post
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missing in vs_clockwork:item/propellor_bearing
[01May2023 14:30:12.922] [Worker-Main-9/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to resolve texture reference: #missingno in alloyed:block/steel_mesh_fence/tri_way
[01May2023 14:30:13.759] [Worker-Main-12/ERROR] [net.minecraft.client.renderer.texture.TextureAtlas/]: Using missing texture, unable to load minecraft:textures/block/copper.png : java.io.FileNotFoundException: minecraft:textures/block/copper.png
[01May2023 14:30:13.826] [Render thread/ERROR] [net.minecraft.Util/]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/desert/houses]' to registry
[01May2023 14:30:13.826] [Render thread/ERROR] [net.minecraft.Util/]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/snowy/houses]' to registry
[01May2023 14:30:13.826] [Render thread/ERROR] [net.minecraft.Util/]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/plains/houses]' to registry
[01May2023 14:30:13.826] [Render thread/ERROR] [net.minecraft.Util/]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/savanna/houses]' to registry
[01May2023 14:30:13.826] [Render thread/ERROR] [net.minecraft.Util/]: Adding duplicate key 'ResourceKey[minecraft:worldgen/template_pool / minecraft:village/taiga/houses]' to registry
[01May2023 14:30:13.850] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Starting version check at https://api.modrinth.com/updates/flywheel/forge_updates.json
[01May2023 14:30:14.445] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [flywheel] Found status: UP_TO_DATE Current: 0.6.8.a Target: null
[01May2023 14:30:14.446] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [controlling] Starting version check at https://updates.blamejared.com/get?n=controlling&gv=1.18.2
[01May2023 14:30:14.778] [Worker-Main-6/INFO] [top.leonx.irisflw.IrisFlw/]: Oculus Flywheel Compat Initialized
[01May2023 14:30:14.989] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [controlling] Found status: BETA Current: 9.0+22 Target: 9.0+22
[01May2023 14:30:14.990] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[01May2023 14:30:15.302] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 40.2.0 Target: null
[01May2023 14:30:15.651] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!
[01May2023 14:30:15.679] [Render thread/ERROR] [net.minecraft.client.Minecraft/]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.util.HashMap.forEach(HashMap.java:1424) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.close(TextureManager.java:177) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?]
	at net.minecraft.client.Minecraft.close(Minecraft.java:979) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?]
	at net.minecraft.client.Minecraft.m_91393_(Minecraft.java:956) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?]
	at net.minecraft.client.main.Main.main(Main.java:221) ~[client-1.18.2-20220404.173914-srg.jar%2369!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.0.jar%2351!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

**Comment by rbasamoyai** [comment]
Do you have a crash log? I can somewhat see the issue here but I think a crash log would show it better.
Also, please put your messages in an easier to read format (e.g. pastebin, code block).

**Comment by NullHarp** [comment]
nvm potato has just informed me im dumb and this is already fixed in the NEWEST nightly, sorry for wasting your time, il close this issue now.
