### ISSUE TITLE
SlidingBreechBlock crashes the game when powder charges or shots get inserted into the cannon

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#2]
```
Description: Ticking block entity

java.lang.AbstractMethodError: Receiver class rbasamoyai.createbigcannons.cannons.cannonend.SlidingBreechBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.level.block.state.BlockState getBlockState()' of interface rbasamoyai.createbigcannons.cannons.ICannonBlockEntity.
	at rbasamoyai.createbigcannons.cannons.ICannonBlockEntity.canLoadBlock(ICannonBlockEntity.java:19) ~[CreateBigCannons-1.18.2.jar%2364!/:1.18.2-0.1-beta] {re:classloading}
	at rbasamoyai.createbigcannons.cannons.cannonend.AbstractCannonBreechBlockEntity.canLoadBlock(AbstractCannonBreechBlockEntity.java:30) ~[CreateBigCannons-1.18.2.jar%2364!/:1.18.2-0.1-beta] {re:classloading}
	at rbasamoyai.createbigcannons.cannons.CannonBehavior.canLoadBlock(CannonBehavior.java:39) ~[CreateBigCannons-1.18.2.jar%2364!/:1.18.2-0.1-beta] {re:classloading}
	at rbasamoyai.createbigcannons.cannonloading.CannonLoaderCollider.isCollidingWithWorld(CannonLoaderCollider.java:80) ~[CreateBigCannons-1.18.2.jar%2364!/:1.18.2-0.1-beta] {re:classloading}
	at rbasamoyai.createbigcannons.cannonloading.CannonLoaderBlockEntity.assemble(CannonLoaderBlockEntity.java:53) ~[CreateBigCannons-1.18.2.jar%2364!/:1.18.2-0.1-beta] {re:classloading}
	at com.simibubi.create.content.contraptions.components.structureMovement.piston.LinearActuatorTileEntity.tick(LinearActuatorTileEntity.java:96) ~[create-mc1.18.2_v0.5.0c.jar%2363!/:mc1.18.2_v0.5.0c] {re:classloading}
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.m_155252_(SmartTileEntityTicker.java:15) ~[create-mc1.18.2_v0.5.0c.jar%2363!/:mc1.18.2_v0.5.0c] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2390!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


```

**Comment by rbasamoyai** [comment]
Hmm, thought that I could get away with some weird method naming so that I could write less code. Thought `BlockEntity#getBlockState` would work, seems not. Will rectify this in next commit.

**Comment by rbasamoyai** [comment]
Should be fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/8435c466037656056452972a28415517b91065ae.
