### ISSUE TITLE
crash in start the game

### ISSUE THREAD

**Issue by micuit-cuit** [Cannoneers-of-Create/CreateBigCannons#353]
<details><summary>log</summary>
<p>

Mods:
  [✔️] AI-Improvements-1.19.2-0.5.2.jar
  [✔️] architectury-6.5.69-forge.jar
  [✔️] balm-forge-1.19.2-4.6.0.jar
  [✔️] canary-mc1.19.2-0.1.9.jar
  [✔️] cc-tweaked-1.19.2-1.101.3.jar
  [✔️] cloth-config-8.2.88-forge.jar
  [✔️] create_enchantment_industry-1.19.2-for-create-0.5.0.i-1.1.14.jar
  [✔️] create_misc_and_things_ 1.19.2_4.0A.jar
  [✔️] create-1.19.2-0.5.0.i.jar
  [✔️] create-confectionery1.19.2_v1.0.9.jar
  [✔️] createbigcannons-forge-1.19.2-0.5.2.jar
  [✔️] CustomPlayerModels-1.19-0.6.11a.jar
  [✔️] Decorative+Blocks-forge-1.19.2-3.0.0.jar
  [✔️] dummmmmmy-1.19.2-1.7.1.jar
  [✔️] Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
  [✔️] FarmersDelight-1.19.2-1.2.3.jar
  [✔️] FastFurnace-1.19.2-7.0.0.jar
  [✔️] FastSuite-1.19.2-4.0.0.jar
  [✔️] ferritecore-5.0.3-forge.jar
  [✔️] flywheel-forge-1.19.2-0.6.8.a.jar
  [✔️] ftb-library-forge-1902.3.15-build.188.jar
  [✔️] ftb-quests-forge-1902.4.9-build.195.jar
  [✔️] ftb-teams-forge-1902.2.12-build.95.jar
  [✔️] garnished-0.8+1.19.2.jar
  [✔️] inventorio-1.19-forge-1.8.7.jar
  [✔️] ironchests-3.1.3-forge.jar
  [✔️] item-filters-forge-1902.2.9-build.46.jar
  [✔️] ItShallNotTick-1.0.11-build.35.jar
  [✔️] Jade-1.19.1-forge-8.8.1.jar
  [✔️] JadeAddons-1.19.2-forge-3.4.0.jar
  [✔️] jei-1.19.2-forge-11.6.0.1013.jar
  [✔️] kotlinforforge-3.11.0-all.jar
  [✔️] moonlight-1.19.2-2.2.23-forge.jar
  [✔️] NaturesCompass-1.19.2-1.10.0-forge.jar
  [✔️] Placebo-1.19.2-7.1.5.jar
  [✔️] sophisticatedbackpacks-1.19.2-3.18.40.779.jar
  [✔️] sophisticatedcore-1.19.2-0.5.38.203.jar
  [✔️] Steam_Rails-1.19.2-1.1.1.jar
  [✔️] StorageDrawers-1.19-11.1.2.jar
  [✔️] voicechat-forge-1.19.2-2.4.24.jar
  [✔️] waystones-forge-1.19.2-11.4.1.jar
  [✔️] worldedit-mod-7.2.12.jar

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 2023-09-24 01:46:39
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.0-universal.jar%23216!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.0-universal.jar%23216!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:inventorio.mixins.json:client.accessor.MinecraftClientAccessor,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:APP:inventorio.mixins.json:client.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23211!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%23126!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23113!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD createbigcannons --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23213!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23212!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Caused by 1: java.lang.NoClassDefFoundError: com/simibubi/create/foundation/item/TooltipModifier
		at rbasamoyai.createbigcannons.forge.CreateBigCannonsForge.<init>(CreateBigCannonsForge.java:44) ~[createbigcannons-forge-1.19.2-0.5.2.jar%23179!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23213!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23212!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /home/micuit-cuit/.local/share/multimc/instances/creatReborn/.minecraft/mods/createbigcannons-forge-1.19.2-0.5.2.jar
	Failure message: Create Big Cannons (createbigcannons) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.5.2-nightly-77aa315
	Mod Issue URL: https://github.com/Cannoneers-of-Create/CreateBigCannons/issues
	Exception message: java.lang.ClassNotFoundException: com.simibubi.create.foundation.item.TooltipModifier
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at rbasamoyai.createbigcannons.forge.CreateBigCannonsForge.<init>(CreateBigCannonsForge.java:44) ~[createbigcannons-forge-1.19.2-0.5.2.jar%23179!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.0.jar%23213!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.0.jar%23212!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.2.0-32-generic
	Java Version: 17.0.8.1, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 321357824 bytes (306 MiB) / 847249408 bytes (808 MiB) up to 7516192768 bytes (7168 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 78 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Skylake GT2 [HD Graphics 520]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x1916
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 13430.37
	Virtual memory used (MB): 9464.61
	Swap memory total (MB): 9537.00
	Swap memory used (MB): 2845.71
	JVM Flags: 2 total; -Xms512m -Xmx7168m
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.11.0
		lowcodefml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |COMMON_SET|Manifest: NOSIGNATURE
		ItShallNotTick-1.0.11-build.35.jar                |It Shall Not Tick             |itshallnottick                |1.0.11-build.35     |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.23-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.23       |COMMON_SET|Manifest: NOSIGNATURE
		createbigcannons-forge-1.19.2-0.5.2.jar           |Create Big Cannons            |createbigcannons              |0.5.2-nightly-77aa31|ERROR     |Manifest: NOSIGNATURE
		create_misc_and_things_ 1.19.2_4.0A.jar           |create: things and misc       |create_things_and_misc        |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.8.1.jar                       |Jade                          |jade                          |8.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1013.jar                  |Just Enough Items             |jei                           |11.6.0.1013         |COMMON_SET|Manifest: NOSIGNATURE
		inventorio-1.19-forge-1.8.7.jar                   |Inventorio                    |inventorio                    |1.8.7               |COMMON_SET|Manifest: NOSIGNATURE
		garnished-0.8+1.19.2.jar                          |Create: Garnished             |garnished                     |0.8+1.19.2          |COMMON_SET|Manifest: NOSIGNATURE
		Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar   |Entity Collision FPS Fix      |entitycollisionfpsfix         |2.0.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.11.0              |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.38.203.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.38.203   |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.1.jar                 |Waystones                     |waystones                     |11.4.1              |COMMON_SET|Manifest: NOSIGNATURE
		ironchests-3.1.3-forge.jar                        |Iron Chests: Restocked        |ironchests                    |3.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		FastSuite-1.19.2-4.0.0.jar                        |Fast Suite                    |fastsuite                     |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.19.2-7.1.5.jar                          |Placebo                       |placebo                       |7.1.5               |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.10.0-forge.jar            |Nature's Compass              |naturescompass                |1.19.2-1.10.0-forge |COMMON_SET|Manifest: NOSIGNATURE
		CustomPlayerModels-1.19-0.6.11a.jar               |Customizable Player Models    |cpm                           |0.6.11a             |COMMON_SET|Manifest: NOSIGNATURE
		canary-mc1.19.2-0.1.9.jar                         |Canary                        |canary                        |0.1.9               |COMMON_SET|Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		create-confectionery1.19.2_v1.0.9.jar             |Create Confectionery          |create_confectionery          |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.20.jar            |Resourceful Lib               |resourcefullib                |1.1.20              |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19.2-3.18.40.779.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.40.779  |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.19.2-7.0.0.jar                      |FastFurnace                   |fastfurnace                   |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.1.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.69-forge.jar                     |Architectury                  |architectury                  |6.5.69              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1902.3.15-build.188.jar         |FTB Library                   |ftblibrary                    |1902.3.15-build.188 |COMMON_SET|Manifest: NOSIGNATURE
		item-filters-forge-1902.2.9-build.46.jar          |Item Filters                  |itemfilters                   |1902.2.9-build.46   |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cc-tweaked-1.19.2-1.101.3.jar                     |CC: Tweaked                   |computercraft                 |1.101.3             |COMMON_SET|Manifest: NOSIGNATURE
		AI-Improvements-1.19.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		Steam_Rails-1.19.2-1.1.1.jar                      |Create: Steam 'n Rails        |railways                      |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		JadeAddons-1.19.2-forge-3.4.0.jar                 |Jade Addons                   |jadeaddons                    |3.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		ftb-teams-forge-1902.2.12-build.95.jar            |FTB Teams                     |ftbteams                      |1902.2.12-build.95  |COMMON_SET|Manifest: NOSIGNATURE
		ftb-quests-forge-1902.4.9-build.195.jar           |FTB Quests                    |ftbquests                     |1902.4.9-build.195  |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.19.2-2.4.24.jar                 |Simple Voice Chat             |voicechat                     |1.19.2-2.4.24       |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		dummmmmmy-1.19.2-1.7.1.jar                        |MmmMmmMmmmmm                  |dummmmmmy                     |1.19.2-1.7.1        |COMMON_SET|Manifest: NOSIGNATURE
		create_enchantment_industry-1.19.2-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.1.14              |COMMON_SET|Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays
	Crash Report UUID: 6c7db95b-a69b-48ac-a54f-33ec2616326e
	FML: 43.2
	Forge: net.minecraftforge:43.2.0[01:46:52] [Render thread/INFO] [minecraft/Minecraft]: Stopping!
Process exited with exit code 0 (0x0).
Veuillez noter que généralement ni le code de sortie, ni sa description ne suffisent pour diagnostiquer les problèmes !
Téléchargez toujours le journal complet et pas seulement le code de sortie.
Clipboard copy at: 24 Sep 2023 01:51:15 +0200

</p>
</details> 
game version:1.19.2
mod version:createbigcannons-forge-1.19.2-0.5.2

**Comment by rbasamoyai** [comment]
Update your Create version to Create 0.5.1.c or downgrade your Create Big Cannons version to 0.5.1.b

**Comment by micuit-cuit** [comment]
ok
