### ISSUE TITLE
java lang error related crash

### ISSUE THREAD

**Issue by randogaming6252** [Cannoneers-of-Create/CreateBigCannons#365]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at rbasamoyai.createbigcannons.forge.ModGroupImpl.useModTab(ModGroupImpl.java:38) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading}
-- MOD createbigcannons --
Details:
	Mod File: /C:/Users/jordan/curseforge/minecraft/Instances/create all the addons/mods/createbigcannons-forge-1.20.1-0.5.2.a.jar
	Failure message: Create Big Cannons (createbigcannons) has failed to load correctly
		java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
	Mod Version: 0.5.2.a-nightly-3b4e734
	Mod Issue URL: https://github.com/Cannoneers-of-Create/CreateBigCannons/issues
	Exception message: java.lang.NoSuchMethodError: 'com.simibubi.create.foundation.data.CreateRegistrate com.simibubi.create.foundation.data.CreateRegistrate.useCreativeTab(net.minecraftforge.registries.RegistryObject)'
Stacktrace:
	at rbasamoyai.createbigcannons.forge.ModGroupImpl.useModTab(ModGroupImpl.java:38) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading}
	at rbasamoyai.createbigcannons.ModGroup.useModTab(ModGroup.java) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading}
	at rbasamoyai.createbigcannons.index.CBCBlocks.<clinit>(CBCBlocks.java:85) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading,re:mixin}
	at rbasamoyai.createbigcannons.CreateBigCannons.init(CreateBigCannons.java:39) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading}
	at rbasamoyai.createbigcannons.forge.CreateBigCannonsForge.<init>(CreateBigCannonsForge.java:50) ~[createbigcannons-forge-1.20.1-0.5.2.a.jar%23223!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.1.jar%23262!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.2.1.jar%23261!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

all there really is to it. cant really describe it better
[crash-2023-10-05_22.00.30-fml.txt](https://github.com/Cannoneers-of-Create/CreateBigCannons/files/12826563/crash-2023-10-05_22.00.30-fml.txt)

**Comment by DampGoodSanta** [comment]
I had exact same problem

**Comment by rbasamoyai** [comment]
Fixed in https://github.com/Cannoneers-of-Create/CreateBigCannons/pull/357
