### ISSUE TITLE
`java.lang.NoSuchMethodError: 'net.minecraft.class_1255`

### ISSUE THREAD

**Issue by bill88t** [Cannoneers-of-Create/CreateBigCannons#537]
Create: 1.20.1 v0.5.1f
CreateBigCannons: 1.20.1-0.5.4
Environment: Fabric
Modlist:
```
	- alternate-current 1.7.0
	- altorigingui 1.0.1
	- animal_origins 1.0.5
	- appleskin 2.5.1+mc1.20
	- architectury 9.2.14
	- artifacts 9.5.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- expandability 9.0.4
	   |-- mixinextras 0.3.5
	   \-- step-height-entity-attribute 1.2.0
	- badpackets 0.4.3
	- bakery 1.1.8
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- beachparty 1.1.4
	- betteradvancements 0.3.2.162
	- betterarcheology 1.1.8-1.20.1
	- betterchunkloading 1.20.1-4.1
	- betterend 4.0.11
	- betterf3 7.0.2
	- betternether 9.0.10
	- betterthanmending 1.3.0
	- betterthirdperson 1.9.0
	- blahaj 0.3.2
	- blockrunner 8.0.4
	- boatbreakfix 1.0.11
	- botarium 2.3.3
	   \-- team_reborn_energy 3.0.0
	- brewery 1.1.6
	- cardinal-components 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- carryon 2.1.2.7
	- chunksending 1.20.1-2.8
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- clumps 12.0.0.4
	- connectivity 1.20.1-5.5
	- controlling 12.0.2
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_config 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_entity 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tool_actions 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_transfer 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_fluids 2.3.2+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_enchantment_industry 1.2.16
	   \-- create_dragon_lib 1.4.2
	- create_jetpack 4.2.0
	   \-- flightlib 2.1.0
	- create_new_age 1.1.2
	- createaddition 1.2.3
	- createbigcannons 0.5.4-nightly-8b9cea6
	   |-- mixinextras 0.3.5
	   \-- ritchiesprojectilelib 1.0.0-369e88d+1.20.1-fabric
	        \-- porting_lib_utility 2.1.1127+1.20
	             \-- porting_lib_gametest 2.1.1127+1.20
	- cullleaves 3.2.0
	   \-- midnightlib 1.4.1
	- cupboard 1.20.1-2.6
	- debugify 1.20.1+2.0
	- deepslatecutting 1.7.0
	- diggusmaximus 1.5.9-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- doapi 1.2.9
	   \-- terraform-wood-api-v1 7.0.1
	- dynamic_fps 3.4.3
	- entityculling 1.6.2-mc1.20.1
	- expandeddelight 0.3.0.3
	   \-- omega-config 1.2.3-1.18.1
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabric_tps 1.20.1-1.4.0
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- fallingleaves 1.15.6
	- fallingtree 4.3.4
	- farmersdelight 1.20.1-1.4.3
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- gpumemleakfix 1.20.1-1.8
	- herbalbrews 1.0.6
	- iceberg 1.1.18
	- indium 1.0.27+mc1.20.1
	- inventorysorter 1.9.0-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- irisflw 0.2.1
	- ironchests 5.0.2
	   \-- resourcefullib 2.0.6
	        \-- com_teamresourceful_yabn 1.0.3
	- java 17
	- jei 15.3.0.4
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- legendarytooltips 1.4.5
	- lithium 0.11.2
	- malilib 0.16.3
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- moborigins 1.11.1
	- modernfix 5.17.0+mc1.20.1
	- modmenu 7.2.2
	- mousetweaks 2.26
	- naturescompass 1.20.1-2.2.3-fabric
	- nethervinery 1.2.10
	- notenoughanimations 1.7.3
	- openpartiesandclaims 0.20.4
	- origins 1.10.0
	   \-- apoli 2.9.0
	        |-- additionalentityattributes 1.3.0+1.20.0
	        |-- calio 1.11.0
	        \-- playerabilitylib 1.8.0
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- pehkui 3.8.0+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- prism 1.0.5
	- puzzleslib 8.1.18
	   \-- puzzlesaccessapi 8.0.7
	- pvpflag 1.3.0+1.20.1
	   |-- cardinal-components-base 5.2.2
	   \-- cardinal-components-entity 5.2.2
	- railways 1.5.3+fabric-mc1.20.1
	   \-- mm 2.3
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- searchables 1.0.3
	- smoke_suppression 1.0.16
	   \-- crowdin-translate 1.4+1.19.3
	- smoothchunk 1.20.1-3.6
	- smwyg 1.1.1
	- sodium 0.5.3
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- spark 1.10.53
	- starlight 1.1.2+fabric.dbc156f
	- stoneworks 8.0.0
	- supermartijn642corelib 1.1.17
	- terrablender 3.0.1.4
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- thiccpackets 1.17-1.19+
	- toms_storage 1.6.6
	- trade_cycling 1.20.1-1.0.7
	- trashcans 1.0.18
	   \-- team_reborn_energy 3.0.0
	- travelersbackpack 1.20.1-9.1.9
	- trinkets 3.7.2
	- tweakeroo 0.17.1
	- vinery 1.4.15
	- visuality 0.7.1+1.20
	- voicechat 1.20.1-2.5.12
	- wakes 0.2.4+1.20.1
	   |-- com_github_jdiemke_delaunay-triangulator_delaunaytriangulator 1.0.0
	   \-- satin 1.14.0
	- wthit 8.9.0
	- xaerominimap 24.1.1
	- xaeroworldmap 1.38.4
	- yet_another_config_lib_v3 3.2.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yigd 2.0.0-beta.11
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- libgui 8.1.1+1.20.1
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- yungsapi 1.20-Fabric-4.0.4
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
```
Server side error trace:
```
[16:54:12] [Netty Epoll Server IO #9/ERROR]: Encountered exception while handling in channel with name "createbigcannons:network"
java.lang.NoSuchMethodError: 'net.minecraft.class_1255 com.simibubi.create.foundation.networking.SimplePacketBase$Context.executor()'
	at rbasamoyai.createbigcannons.fabric.network.FabricPacket.handle(FabricPacket.java:28) ~[createbigcannons-fabric-1.20.1-0.5.4.jar:?]
	at com.simibubi.create.foundation.networking.SimplePacketBase.handle(SimplePacketBase.java:37) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at me.pepperbell.simplenetworking.SimpleChannel$C2SHandler.receive(SimpleChannel.java:249) ~[porting_lib_networking-2.3.0+1.20.1-46ea1a0d0a7b8734.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.minecraft.class_3244.handler$cab000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2500) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[server-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[16:54:12] [Netty Epoll Server IO #9/ERROR]: Exception occurred in netty pipeline
java.lang.NoSuchMethodError: 'net.minecraft.class_1255 com.simibubi.create.foundation.networking.SimplePacketBase$Context.executor()'
	at rbasamoyai.createbigcannons.fabric.network.FabricPacket.handle(FabricPacket.java:28) ~[createbigcannons-fabric-1.20.1-0.5.4.jar:?]
	at com.simibubi.create.foundation.networking.SimplePacketBase.handle(SimplePacketBase.java:37) ~[create-fabric-0.5.1-f-build.1335+mc1.20.1.jar:?]
	at me.pepperbell.simplenetworking.SimpleChannel$C2SHandler.receive(SimpleChannel.java:249) ~[porting_lib_networking-2.3.0+1.20.1-46ea1a0d0a7b8734.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:85) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:39) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:80) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.minecraft.class_3244.handler$cab000$fabric-networking-api-v1$handleCustomPayloadReceivedAsync(class_3244.java:2500) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) ~[server-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[server-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[16:54:12] [Server thread/INFO]: bill88t lost connection: Internal Exception: java.lang.NoSuchMethodError: 'net.minecraft.class_1255 com.simibubi.create.foundation.networking.SimplePacketBase$Context.executor()'
[16:54:12] [Server thread/INFO]: bill88t left the game
```
The client side does not produce a log regarding this. It just notes the disconnection.
This error happens is several interactions with Create: Big Cannons items.
The easiest to reproduce this is with the ammo container. Opening it, kicks the player in about 3 seconds.

This doesn't happen in singleplayer, but only in multiplayer.

**Comment by bill88t** [comment]
Server was caching mods.. smh
