### ISSUE TITLE
Crash when adding Create Big Cannons mod (exit code 0)

### ISSUE THREAD

**Issue by repryty** [Cannoneers-of-Create/CreateBigCannons#618]
hello,

I'm using several mods together, and when I add the Create Big Cannons mod, the game crashes and gives me an exit code of 0.

I've checked the logs, but I can't find the exact cause of the crash, is there any chance you can find the cause of the problem in the logs?

# GDLauncher Crash Report
```
Description: Initializing game

java.lang.NoClassDefFoundError: dev/emi/trinkets/api/client/TrinketRenderer
	at rbasamoyai.createbigcannons.fabric.CBCClientFabric.onModsLoaded(CBCClientFabric.java:85)
	at io.github.fabricators_of_create.porting_lib.event.common.ModsLoadedCallback.lambda$static$0(ModsLoadedCallback.java:13)
	at net.minecraft.class_310.handler$zfg000$porting_lib_base$port_lib$modsLoaded(class_310.java:3063)
	at net.minecraft.class_310
```
GDLauncher provided the information above.

# environments
- Windows 11
- Minecraft 11
- GDLauncher 2.0.20
- Java 17
- Fabric 0.16.0
- Create Big Cannons 5.5.0
- Create Fabric 0.5.1
- Other modes can be seen in the logfiles

# attachment
- [latest.log](https://github.com/user-attachments/files/16358560/latest.log)

**Comment by repryty** [comment]
It was because Trinkets mod was not installed!
